(()=>{
const THEME_KEY='shturman-theme', LOCAL_USERS='shturman-users', LOCAL_SESSION='shturman-local-session';
const D=window.TRAINING_DATA,B=D.blocks,Q=D.questions.filter(q=>q.eligible),THEORY=window.THEORY;
const V=document.getElementById('view'),crumb=document.getElementById('crumb');
const KEY='shturman-v7'; let S={blocks:{},exam:null,mistakes:{}},quiz=null,AUTH={mode:'local',user:null,ready:false};
function applyTheme(){const t=localStorage.getItem(THEME_KEY)||'light';document.documentElement.dataset.theme=t;const b=document.getElementById('themeToggle');if(b){b.textContent=t==='dark'?'☀':'☾';b.title=t==='dark'?'Включить светлую тему':'Включить тёмную тему'}}
function esc(x){return String(x??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function sh(a){a=[...a];for(let i=a.length-1;i;i--){let j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function letters(i){return String.fromCharCode(65+i)} function bq(id){return D.questions.filter(q=>q.block===id)} function be(id){return Q.filter(q=>q.block===id)}
function passed(id){return !!S.blocks[id]?.passed} function unlocked(i){return true} function passedCount(){return B.filter(b=>passed(b.id)).length} function pct(){return S.exam?.passed?100:Math.round(passedCount()/B.length*100)}
function localStateKey(){return KEY+'::'+(AUTH.user?.username||'guest')}
function loadLocal(){try{return JSON.parse(localStorage.getItem(localStateKey()))||{blocks:{},exam:null,mistakes:{}}}catch{return{blocks:{},exam:null,mistakes:{}}}}
async function loadState(){if(AUTH.mode==='cloud'){try{const r=await fetch('/api/progress',{credentials:'include'});if(r.ok){S=await r.json();return}}catch{}}S=loadLocal()}
let saveTimer=null; async function save(){localStorage.setItem(localStateKey(),JSON.stringify(S)); side(); if(AUTH.mode==='cloud'){clearTimeout(saveTimer);saveTimer=setTimeout(async()=>{try{await fetch('/api/progress',{method:'POST',headers:{'Content-Type':'application/json'},credentials:'include',body:JSON.stringify(S)})}catch{}},120)}}
function side(){const p=pct();document.getElementById('sidePct').textContent=p+'%';document.getElementById('sideBar').style.width=p+'%';document.getElementById('sideText').textContent=`${passedCount()} из ${B.length} блоков`;const u=document.getElementById('userName');if(u)u.textContent=AUTH.user?.username||'Гость';const mode=document.querySelector('.local');if(mode)mode.innerHTML=`<i></i> ${AUTH.mode==='cloud'?'Облачный режим':'Локальный режим'}`;const an=document.getElementById('adminNav');if(an)an.style.display=AUTH.user?.role==='admin'?'flex':'none'}
function go(x){location.hash=x} function nav(route){document.querySelectorAll('.nav').forEach(x=>x.classList.toggle('active',x.dataset.route===route))}
function render(){if(!AUTH.ready)return;let raw=(location.hash||'#dashboard').slice(1),p=raw.split('/'),r=p[0];if(r==='reset'){resetScreen(decodeURIComponent(p.slice(1).join('/')));return}side();if(r==='dashboard'){nav('dashboard');crumb.textContent='Обзор';dashboard()}else if(r==='course'){nav('course');crumb.textContent='Обучение';course()}else if(r==='block'){nav('course');block(p[1])}else if(r==='quiz'){nav('course');start('block',p[1])}else if(r==='lab'){nav('lab');crumb.textContent='Буи и огни';lab()}else if(r==='mistakes'){nav('mistakes');crumb.textContent='Мои ошибки';mistakes()}else if(r==='exam'){nav('exam');crumb.textContent='Экзамен';exam()}else if(r==='profile'){profile()}else if(r==='admin'){if(AUTH.user?.role!=='admin')return go('dashboard');adminPage()}else go('dashboard');window.scrollTo({top:0,behavior:'smooth'})}
function dashboard(){let i=B.findIndex((b,i)=>unlocked(i)&&!passed(b.id)),n=i<0?null:B[i];V.innerHTML=`<section class="hero animate"><div><div class="eyebrow">Локальная учебная платформа</div><h1>Подготовка без лишнего шума.</h1><p>Изучай материал в удобном порядке, тренируйся на реальных вопросах и сразу разбирай ошибки. Отдельная лаборатория помогает отработать буи и навигационные огни.</p></div><div class="hero-actions"><button class="btn btn-primary" onclick="location.hash='${n?'block/'+n.id:'exam'}'">${n?'Продолжить обучение':'Открыть экзамен'} →</button></div></section><section class="stats"><div class="stat"><div class="top"><div class="ring" style="--deg:${pct()*3.6}deg"><b>${pct()}%</b></div><div><b>${passedCount()}/${B.length}</b><span>блоков пройдено</span></div></div></div><div class="stat"><b>${Q.length}</b><span>вопросов в тестовом банке</span></div><div class="stat"><b>9 / 12</b><span>проходной балл финала</span></div></section><div class="section-head"><h2>Траектория обучения</h2><span>последовательное прохождение</span></div><section class="grid">${B.map(card).join('')}</section>`}
function card(b,i){let ok=passed(b.id),u=unlocked(i),at=!!S.blocks[b.id]?.attempted;return `<article class="course ${u?'':'locked'} animate" onclick="${u?`location.hash='block/${b.id}'`:''}"><div class="course-top"><div class="icon">${b.icon}</div><div><h3>${i+1}. ${esc(b.title)}</h3><p>${esc(b.description)}</p></div></div><div class="mini"><i style="width:${ok?100:0}%"></i></div><div class="course-foot"><span>${bq(b.id).length} вопросов</span><span class="badge ${ok?'passed':(at?'fail':'open')}">${ok?'✓ Пройдено':(at?'↻ Повторить':'● Доступен')}</span></div></article>`}
function theoryFor(id){if(id==='buoys')return THEORY.buoys;if(id==='lights')return THEORY.lights;if(id==='rules')return THEORY.rules;return THEORY.common.slice(0,2)}
function block(id){let b=B.find(x=>x.id===id);if(!b)return go('course');let i=B.indexOf(b);let qs=bq(id);V.innerHTML=`<div class="detail animate"><button class="back" onclick="location.hash='course'">← Вернуться к программе</button><section class="detail-head"><div class="eyebrow">Блок ${i+1} из ${B.length}</div><h1>${esc(b.title)}</h1><p>${esc(b.description)}</p><div class="chips"><span class="chip">${qs.length} вопросов</span><span class="chip">Тест: до ${Math.min(10,be(id).length)} вопросов</span><span class="chip">Порог: 80%</span></div></section><div class="section-head"><h2>Теория</h2><span>сначала понять, потом отвечать</span></div><section class="theory">${theoryFor(id).map(x=>`<article class="theory-card"><h3>${esc(x.title)}</h3><p>${esc(x.text)}</p></article>`).join('')}</section><div class="section-head"><h2>Разбор вопросов</h2><span>правильный ответ доступен до теста</span></div>${qs.map(q=>{let a=q.options.filter((_,j)=>q.correct[j]);return `<article class="learn animate"><div class="q">Вопрос ${q.number}</div><h3>${esc(q.prompt)}</h3>${q.images?.[0]?`<img class="qimg" src="${esc(q.images[0])}" alt="">`:''}<div class="answer"><strong>Ответ по материалу</strong>${a.length?a.map(esc).join('<br>'):'Ответ не определён'}</div></article>`}).join('')}<div class="detail-actions"><button class="btn btn-primary" onclick="location.hash='quiz/${b.id}'">${passed(id)?'Повторить тест':'Пройти контрольный тест'} →</button></div></div>`}
function course(){V.innerHTML=`<section class="hero animate"><div><div class="eyebrow">Программа</div><h1>Учебные блоки</h1><p>Каждый блок можно открыть и пройти отдельно в любом порядке. После завершения всех блоков открывается итоговый экзамен.</p></div></section><div class="section-head"><h2>Все блоки</h2><span>${B.length} этапов</span></div><section class="grid">${B.map(card).join('')}</section>`}
const BUOY_DAY_NUMBERS=[3485,3486,3487,3488,3489,3495,3496,3497,3498,3499,3500,3501,3502,3503,3504,3505,3506,3507,3508,3509];
const BUOY_NIGHT_MAP={3485:3490,3486:3491,3487:3492,3488:3493,3489:3494,3495:3510,3496:3511,3497:3512,3498:3513,3499:3514,3500:3515,3501:3516,3502:3517,3503:3518,3505:3519};
function qby(n){return D.questions.find(q=>q.number===n)}
function correctText(q){return q?.options?.filter((_,i)=>q.correct[i])[0]||''}
function cardOptions(q){if(!q)return[];let c=correctText(q);let pool=q.options.filter(x=>x!==c);return sh([c,...sh(pool).slice(0,3)])}
function makeBuoyCards(){return BUOY_DAY_NUMBERS.map(day=>{let dq=qby(day),night=BUOY_NIGHT_MAP[day],nq=night?qby(night):null;return {day,night,image:dq?.images?.[0],meaning:correctText(dq),meaningOptions:cardOptions(dq),light:nq?correctText(nq):null,lightOptions:nq?cardOptions(nq):[],dayPrompt:dq?.prompt||'Что обозначает этот знак?',nightPrompt:nq?.prompt||'В исходном банке нет отдельного вопроса о ночном огне этого знака.',hasNight:!!nq}})}
function lab(){let cards=makeBuoyCards(),complete=cards.filter(c=>c.hasNight).length,missing=cards.length-complete;V.innerHTML=`<section class="hero animate"><div><div class="eyebrow">Отдельный тренажёр</div><h1>Буи и их огни</h1><p>Здесь не нужно проходить общий курс. Открывай этот раздел отдельно и тренируй именно навигационные знаки из исходного банка: случайная карточка, значение знака и ночная характеристика.</p></div><div class="hero-actions"><button class="btn btn-primary" onclick="window.buoyTest('complete')">Тест →</button><button class="btn btn-secondary" onclick="window.buoyTest('all')">Весь банк</button></div></section><section class="stats"><div class="stat"><b>${cards.length}</b><span>дневных знаков в банке</span></div><div class="stat"><b>${complete}</b><span>знаков с парой ночного вопроса</span></div><div class="stat"><b>${missing}</b><span>знаков без отдельного ночного вопроса</span></div></section><div class="section-head"><h2>Как это работает</h2><span>случайная карточка → ответ → разбор</span></div><section class="theory"><article class="theory-card"><h3>① Что обозначает?</h3><p>Сначала смотри на изображение и выбирай значение только из вариантов исходного банка.</p></article><article class="theory-card"><h3>② Как горит ночью?</h3><p>Если в исходном банке есть соответствующий ночной вопрос, он появляется второй частью карточки. Мы не придумываем отсутствующие данные.</p></article><article class="theory-card"><h3>③ Сразу видишь ошибку</h3><p>После проверки показываются твой ответ, правильный ответ и номера исходных вопросов.</p></article></section><div class="section-head"><h2>Весь банк</h2><span>${cards.length} знаков</span></div><section class="buoy-bank-grid">${cards.map(c=>`<article class="buoy-bank-card"><div class="buoy-bank-image"><img src="${esc(c.image)}" alt="Знак ${c.day}"></div><div class="buoy-bank-info"><div class="source-tags"><span>День · №${c.day}</span>${c.hasNight?`<span>Ночь · №${c.night}</span>`:`<span>Ночной вопрос отсутствует</span>`}</div><b>${esc(c.meaning)}</b>${c.hasNight?`<small>${esc(c.light)}</small>`:`<small>Ночная характеристика не вынесена отдельным вопросом в исходном банке.</small>`}</div></article>`).join('')}</section>`}
window.buoyTest=(mode='complete')=>{let all=makeBuoyCards(),items=mode==='all'?all:all.filter(c=>c.hasNight);items=sh(items);quiz={type:'buoyCards',id:'buoys',mode,items,answers:Array(items.length).fill(null),index:0,score:0,checked:false};renderBuoyCard()};
window.buoyChoose=(kind,index)=>{if(!quiz||quiz.type!=='buoyCards'||quiz.checked)return;let c=quiz.items[quiz.index];let opts=kind==='meaning'?c.meaningOptions:c.lightOptions;let value=opts[index];if(value==null)return;let a=quiz.answers[quiz.index]||{meaning:null,light:null};a={...a,[kind]:value};quiz.answers[quiz.index]=a;renderBuoyCard()};
window.buoyCheck=()=>{if(!quiz||quiz.type!=='buoyCards')return;let a=quiz.answers[quiz.index]||{};let c=quiz.items[quiz.index];if(a.meaning==null||(c.hasNight&&a.light==null))return;quiz.checked=true;let ok=a.meaning===c.meaning&&(!c.hasNight||a.light===c.light);if(ok)quiz.score++;renderBuoyCard()};
window.buoyNext=()=>{if(!quiz||quiz.type!=='buoyCards'||!quiz.checked)return;if(quiz.index===quiz.items.length-1){let total=quiz.items.length,score=quiz.score;V.innerHTML=`<section class="result-main animate"><div class="result-icon">${score===total?'✓':'!'}</div><div class="eyebrow">Тренировка завершена</div><h1>${score} / ${total}</h1><p>${score===total?'Идеально.':'Тренировка закончена. Повтори карточки, где были ошибки.'}</p><div class="result-actions"><button class="btn btn-primary" onclick="window.buoyTest('${quiz.mode}')">Ещё раз</button><button class="btn btn-secondary" onclick="location.hash='lab'">Вернуться к буям</button></div></section>`;return}quiz.index++;quiz.checked=false;renderBuoyCard()};
function renderBuoyCard(){let c=quiz.items[quiz.index],a=quiz.answers[quiz.index]||{},pct=Math.round((quiz.index/quiz.items.length)*100),meaningOpts=c.meaningOptions,lightOpts=c.lightOptions,mWrong=quiz.checked&&a.meaning!==c.meaning,lWrong=c.hasNight&&quiz.checked&&a.light!==c.light;V.innerHTML=`<div class="buoy-test animate"><div class="quiz-top"><div><div class="eyebrow">Буи и ночные огни</div><h1>Карточка ${quiz.index+1} из ${quiz.items.length}</h1></div><div class="counter">${quiz.score} верно</div></div><div class="quizbar"><i style="width:${pct}%"></i></div><article class="buoy-test-card"><div class="buoy-image-wrap"><img src="${esc(c.image)}" alt="Навигационный знак ${c.day}"></div><div class="source-tags"><span>День · №${c.day}</span>${c.hasNight?`<span>Ночь · №${c.night}</span>`:`<span>Ночь · данных нет в банке</span>`}</div><div class="buoy-question"><div class="qtag">1. Значение знака</div><h2>${esc(c.dayPrompt)}</h2><div class="buoy-options">${meaningOpts.map((o,i)=>`<button class="buoy-option ${a.meaning===o?'selected':''} ${quiz.checked&&o===c.meaning?'correct':''} ${quiz.checked&&a.meaning===o&&o!==c.meaning?'wrong':''}" onclick="window.buoyChoose('meaning',${JSON.stringify(o).replace(/</g,'\\u003c')})"><span>${String.fromCharCode(65+i)}</span>${esc(o)}</button>`).join('')}</div>${mWrong?`<div class="buoy-feedback wrong-box"><b>❌ Значение неверное</b><strong>${esc(c.meaning)}</strong><small>Правильный ответ · вопрос ${c.day}</small></div>`:''}</div><div class="buoy-question"><div class="qtag">2. Ночной огонь</div><h2>${esc(c.nightPrompt)}</h2>${c.hasNight?`<div class="buoy-options">${lightOpts.map((o,i)=>`<button class="buoy-option ${a.light===o?'selected':''} ${quiz.checked&&o===c.light?'correct':''} ${quiz.checked&&a.light===o&&o!==c.light?'wrong':''}" onclick="window.buoyChoose('light',${JSON.stringify(o).replace(/</g,'\\u003c')})"><span>${String.fromCharCode(65+i)}</span>${esc(o)}</button>`).join('')}</div>${lWrong?`<div class="buoy-feedback wrong-box"><b>❌ Ночной огонь неверный</b><strong>${esc(c.light)}</strong><small>Правильный ответ · вопрос ${c.night}</small></div>`:''}`:`<div class="buoy-source-note">В исходном банке для этого знака нет отдельного вопроса о ночном огне. В тесте оценивается только значение знака — без догадок и добавленных данных.</div>`}${quiz.checked&&!mWrong&&!lWrong?`<div class="buoy-feedback right-box"><b>✓ Всё правильно</b><span>${c.hasNight?'Оба ответа совпали с исходным банком.':'Ответ совпал с исходным банком.'}</span></div>`:''}</div></article><div class="buoy-foot"><button class="btn btn-secondary" onclick="location.hash='lab'">Выйти</button><button class="btn btn-primary" ${a.meaning==null||(c.hasNight&&a.light==null)?'disabled':''} onclick="${quiz.checked?'window.buoyNext()':'window.buoyCheck()'}">${quiz.checked?(quiz.index===quiz.items.length-1?'Завершить':'Следующая карточка →'):'Проверить'}</button></div></div>`}
window.openQuestion=n=>{let c=makeBuoyCards().find(x=>x.day===n);if(c){quiz={type:'buoyCards',id:'buoys',mode:'single',items:[c],answers:[null],index:0,score:0,checked:false};renderBuoyCard();return}let q=Q.find(x=>x.number===n);if(!q)return;quiz={type:'lab',id:'lab',items:[q],answers:[null],index:0};renderQuiz()};
window.labQuiz=()=>window.buoyTest('complete');
function start(type,id){if(type==='block'){let b=B.find(x=>x.id===id),i=B.indexOf(b);if(!b)return go('course');let pool=sh(be(id)).slice(0,Math.min(10,be(id).length));quiz={type,id,items:pool,answers:Array(pool.length).fill(null),index:0};renderQuiz()}else if(type==='exam'){let pool=sh(Q).slice(0,12);quiz={type,id,items:pool,answers:Array(12).fill(null),index:0};renderQuiz()}}
function renderQuiz(){let q=quiz.items[quiz.index],a=quiz.answers[quiz.index],arr=Array.isArray(a)?a:(a==null?[]:[a]);V.innerHTML=`<div class="quiz animate"><div class="quiz-top"><div><div class="eyebrow">${quiz.type==='exam'?'Итоговый экзамен':quiz.type==='lab'?'Визуальная тренировка':'Контрольный тест'}</div><h1>${quiz.type==='exam'?'12 вопросов из всего курса':quiz.type==='lab'?'Буи и навигационные огни':esc(B.find(b=>b.id===quiz.id)?.title||'Блок')}</h1></div><div class="counter">${quiz.index+1} / ${quiz.items.length}</div></div><div class="quizbar"><i style="width:${Math.round((quiz.index+1)/quiz.items.length*100)}%"></i></div><article class="qcard"><div class="qtag">Вопрос ${q.number}</div><h2>${esc(q.prompt)}</h2>${q.multi?'<div class="multi-note">Выбери все правильные варианты</div>':''}${q.images?.[0]?`<img class="qimg" src="${esc(q.images[0])}" alt="Иллюстрация к вопросу ${q.number}">`:''}<div class="options">${q.options.map((o,i)=>`<button class="option ${arr.includes(i)?'selected':''}" onclick="window.pick(${i})"><span class="letter">${letters(i)}</span><span class="otext">${esc(o)}</span></button>`).join('')}</div></article><div class="quiz-foot"><div class="dots">${quiz.items.map((_,i)=>`<button class="dot ${quiz.answers[i]!=null?'done':''} ${i===quiz.index?'current':''}" onclick="window.jump(${i})"></button>`).join('')}</div><div><button class="btn btn-secondary" onclick="window.leaveQuiz()">Выйти</button> <button class="btn btn-primary" ${a==null?'disabled':''} onclick="window.next()">${quiz.index===quiz.items.length-1?'Завершить':'Следующий →'}</button></div></div></div>`}
window.pick=i=>{let q=quiz.items[quiz.index];if(q.multi){let a=Array.isArray(quiz.answers[quiz.index])?[...quiz.answers[quiz.index]]:[];a=a.includes(i)?a.filter(x=>x!==i):[...a,i];quiz.answers[quiz.index]=a.length?a:null}else quiz.answers[quiz.index]=i;renderQuiz()};window.jump=i=>{quiz.index=i;renderQuiz()};window.next=()=>{if(quiz.answers[quiz.index]==null)return;if(quiz.index<quiz.items.length-1){quiz.index++;renderQuiz()}else finish()};window.leaveQuiz=()=>{let r=quiz?.type==='exam'?'exam':quiz?.type==='lab'?'lab':'course';quiz=null;go(r)};
function correct(q,a){let e=q.correct.map((x,i)=>x?i:null).filter(x=>x!==null).sort((a,b)=>a-b),g=(Array.isArray(a)?a:(a==null?[]:[a])).slice().sort((a,b)=>a-b);return e.length===g.length&&e.every((x,i)=>x===g[i])}
function txt(q,a){let x=(Array.isArray(a)?a:(a==null?[]:[a])).filter(i=>q.options[i]!=null).map(i=>q.options[i]);return x.length?x.map(esc).join('<br>'):'Нет ответа'}
function finish(){let items=quiz.items.map((q,i)=>({q,a:quiz.answers[i],ok:correct(q,quiz.answers[i])})),score=items.filter(x=>x.ok).length,total=items.length;items.filter(x=>!x.ok).forEach(x=>{let n=x.q.number;S.mistakes[n]=(S.mistakes[n]||0)+1});if(quiz.type==='block'){let old=S.blocks[quiz.id]||{};S.blocks[quiz.id]={...old,attempted:true,passed:score/total>=.8,bestScore:Math.max(old.bestScore||0,score),lastScore:score}}if(quiz.type==='exam'){S.exam={attempted:true,passed:score>=9,bestScore:Math.max(S.exam?.bestScore||0,score),lastScore:score}}save();let title=quiz.type==='exam'?'Итоговый экзамен':quiz.type==='lab'?'Визуальная тренировка':B.find(b=>b.id===quiz.id)?.title||'Тест';quiz=null;result(score,total,title,items)}
function result(score,total,title,items){let pass=title==='Итоговый экзамен'?score>=9:title==='Визуальная тренировка'?true:score/total>=.8,mistakes=items.filter(x=>!x.ok);V.innerHTML=`<div class="result animate"><section class="result-main ${pass?'':'bad'}"><div class="result-icon">${pass?'✓':'×'}</div><div class="eyebrow">Результат</div><h1>${pass?'Отлично!':'Нужно ещё немного'}</h1><div class="score">${score} / ${total}</div><p>${title==='Итоговый экзамен'?(pass?'Порог 9/12 выполнен.':'Для сдачи нужно минимум 9/12.'):(pass?'Тест пройден.':'Нужно набрать не менее 80%.')}</p><div class="result-stats"><div><b>${score}</b><span>правильных</span></div><div><b>${total-score}</b><span>ошибок</span></div><div><b>${Math.round(score/total*100)}%</b><span>результат</span></div></div><div class="actions"><button class="btn btn-secondary" onclick="location.hash='dashboard'">На главную</button><button class="btn btn-primary" onclick="location.hash='${title==='Итоговый экзамен'?'exam':title==='Визуальная тренировка'?'lab':'course'}'">Продолжить →</button></div></section><section class="review"><div class="section-head"><h2>${mistakes.length?'Ошибки и правильные ответы':'Ошибок нет'}</h2><span>${mistakes.length?mistakes.length+' ошибок':'Все ответы верны'}</span></div>${mistakes.map(x=>`<article class="mistake"><h3>Вопрос ${x.q.number}: ${esc(x.q.prompt)}</h3>${x.q.images?.[0]?`<img class="qimg" src="${esc(x.q.images[0])}" alt="">`:''}<div class="ans wrong"><b>Ваш ответ</b>${txt(x.q,x.a)}</div><div class="ans right"><b>Правильный ответ</b>${x.q.options.filter((_,i)=>x.q.correct[i]).map(esc).join('<br>')}</div></article>`).join('')}</section></div>`}
function exam(){let ok=passedCount()===B.length,best=S.exam?.bestScore;V.innerHTML=`<div class="exam animate"><section class="exam-hero"><div class="eyebrow" style="color:#a9bbff">Финальный этап</div><h1>Итоговый экзамен</h1><p>Новый запуск выбирает 12 случайных вопросов по всему курсу. Для сдачи нужно минимум 9 правильных.</p><div class="rules"><div class="rule"><b>12</b><span>случайных вопросов</span></div><div class="rule"><b>9 / 12</b><span>минимум для сдачи</span></div><div class="rule"><b>∞</b><span>попыток</span></div></div></section>${ok?`<div class="exam-box"><h2>${best!=null?'Лучший результат: '+best+'/12':'Готов к экзамену'}</h2><p style="color:#6c788b">Новый запуск создаст новую случайную выборку.</p><button class="btn btn-primary" onclick="window.startExam()">Начать экзамен →</button></div>`:`<div class="locked-box"><b>Экзамен пока закрыт</b><br>Пройди все ${B.length} учебных блоков. Сейчас готово: ${passedCount()} из ${B.length}.</div>`}</div>`}
window.startExam=()=>start('exam','final');
function mistakes(){let nums=Object.keys(S.mistakes).map(Number).sort((a,b)=>S.mistakes[b]-S.mistakes[a]);if(!nums.length){V.innerHTML=`<section class="hero animate"><div><div class="eyebrow">Повторение</div><h1>Ошибок пока нет.</h1><p>Когда в тесте будет ошибка, вопрос автоматически появится здесь для повторения.</p></div></section>`;return}let qs=nums.map(n=>D.questions.find(q=>q.number===n)).filter(Boolean);V.innerHTML=`<section class="hero animate"><div><div class="eyebrow">Умное повторение</div><h1>Мои ошибки</h1><p>Вопросы, на которых ты ошибался хотя бы один раз. Чем чаще ошибка — тем выше она в списке.</p></div></section><div class="section-head"><h2>${qs.length} вопросов</h2><span>нажми на карточку для тренировки</span></div><section class="grid">${qs.map(q=>`<article class="course" onclick="window.openQuestion(${q.number})"><div class="course-top"><div class="icon">↺</div><div><h3>Вопрос ${q.number}</h3><p>${esc(q.prompt)}</p></div></div><div class="course-foot"><span>Ошибок: ${S.mistakes[q.number]}</span><span class="badge fail">Повторить</span></div></article>`).join('')}</section>`}
async function adminPage(){
  V.innerHTML=`<section class="hero animate"><div><div class="eyebrow">Панель управления</div><h1>Пользователи</h1><p>Прогресс, результаты экзамена и ошибки курсантов. Здесь же можно сбросить прогресс отдельного пользователя.</p></div></section><section class="admin-toolbar"><button class="btn btn-secondary" onclick="window.loadAdmin()">↻ Обновить</button><span id="adminStatus">Загрузка…</span></section><section class="admin-table-wrap"><div id="adminTable"></div></section>`;await loadAdmin()}
window.loadAdmin=async()=>{const st=document.getElementById('adminStatus'),box=document.getElementById('adminTable');if(!st||!box)return;st.textContent='Загрузка…';try{const r=await fetch('/api/admin/users',{credentials:'include',cache:'no-store'});const d=await r.json();if(!r.ok)throw Error(d.error||'Не удалось загрузить пользователей');st.textContent=`${d.users.length} пользователей`;box.innerHTML=`<div class="admin-table"><div class="admin-row admin-head"><b>Пользователь</b><b>Прогресс</b><b>Экзамен</b><b>Ошибки</b><b>Дата</b><b>Действия</b></div>${d.users.map(u=>`<div class="admin-row"><div><strong>${esc(u.username)}</strong>${u.role==='admin'?'<span class="admin-badge">ADMIN</span>':''}</div><div>${u.blocksPassed}/${B.length} блоков</div><div>${u.examBest!=null?u.examBest+'/12':u.examPassed?'сдан':'—'}</div><div>${u.mistakes}</div><div>${esc(String(u.updated_at||u.created_at||'').replace('T',' ').slice(0,16))}</div><div class="admin-actions"><button class="mini-btn" onclick="window.adminReset(${u.id},'${esc(u.username)}')">Сбросить</button>${u.id!==AUTH.user.id?`<button class="mini-btn danger-mini" onclick="window.adminDelete(${u.id},'${esc(u.username)}')">Удалить</button>`:''}</div></div>`).join('')}</div>`}catch(e){st.textContent='Ошибка';box.innerHTML=`<div class="locked-box">${esc(e.message)}</div>`}};
window.adminReset=async(id,name)=>{if(!confirm(`Сбросить прогресс пользователя «${name}»?`))return;const r=await fetch('/api/admin/user',{method:'POST',headers:{'Content-Type':'application/json'},credentials:'include',body:JSON.stringify({id,action:'reset'})});const d=await r.json();if(!r.ok)return toast(d.error||'Ошибка');toast('Прогресс сброшен');loadAdmin()};window.adminDelete=async(id,name)=>{if(!confirm(`Удалить пользователя «${name}» без возможности восстановления?`))return;const r=await fetch('/api/admin/user',{method:'POST',headers:{'Content-Type':'application/json'},credentials:'include',body:JSON.stringify({id,action:'delete'})});const d=await r.json();if(!r.ok)return toast(d.error||'Ошибка');toast('Пользователь удалён');loadAdmin()};
async function profile(){
  let exam=S.exam, email='';
  if(AUTH.mode==='cloud'){
    try{const r=await fetch('/api/profile',{credentials:'include',cache:'no-store'});if(r.ok){const d=await r.json();email=d.user?.email||''}}catch{}
  }
  V.innerHTML=`<section class="profile-head animate"><div class="avatar">${esc((AUTH.user?.username||'U').slice(0,1).toUpperCase())}</div><div><div class="eyebrow">Профиль</div><h1>${esc(AUTH.user?.username||'Гость')}</h1><p>${AUTH.mode==='cloud'?'Синхронизация включена':'Локальный режим — данные хранятся в этом браузере'}</p></div><button class="btn btn-secondary" onclick="window.logout()">Выйти</button></section><section class="stats"><div class="stat"><b>${pct()}%</b><span>общий прогресс</span></div><div class="stat"><b>${passedCount()}/${B.length}</b><span>блоков</span></div><div class="stat"><b>${exam?.bestScore!=null?exam.bestScore+'/12':'—'}</b><span>лучший экзамен</span></div></section><section class="profile-panel"><h2>Восстановление пароля</h2><p>Привяжи email. Если забудешь пароль, на него можно будет получить одноразовую ссылку для восстановления.</p><form id="emailForm" class="profile-email-form"><label>Email<input type="email" name="email" value="${esc(email)}" maxlength="254" placeholder="name@example.com" required></label><button class="btn btn-primary">${email?'Обновить email':'Сохранить email'}</button></form><p class="profile-note">Email нужен только для восстановления доступа. Пароль мы по почте не отправляем.</p></section><section class="profile-panel"><h2>Учебная статистика</h2><p>Ошибок в истории: <b>${Object.keys(S.mistakes).length}</b>. Попыток экзамена: <b>${exam?.attempted?'есть':'нет'}</b>.</p></section>`;
  const form=document.getElementById('emailForm'); if(form)form.onsubmit=async e=>{e.preventDefault();const email=new FormData(e.currentTarget).get('email');try{if(AUTH.mode!=='cloud')throw Error('В локальном режиме email сохраняется только на этом устройстве');const r=await fetch('/api/profile',{method:'POST',headers:{'Content-Type':'application/json'},credentials:'include',body:JSON.stringify({email})});const d=await r.json();if(!r.ok)throw Error(d.error||'Не удалось сохранить email');toast('Email сохранён');profile()}catch(x){toast(x.message)}};
}
async function authRequest(action,body){const r=await fetch('/api/'+action,{method:'POST',headers:{'Content-Type':'application/json'},credentials:'include',body:JSON.stringify(body)});let d={};try{d=await r.json()}catch{}if(!r.ok)throw new Error(d.error||'Не удалось выполнить запрос');return d}
function authScreen(error=''){document.body.classList.add('auth-open');V.innerHTML=`<div class="auth-shell"><div class="auth-card animate"><div class="auth-logo">⚓</div><div class="eyebrow">Штурман</div><h1>Вход в обучение</h1><p class="auth-sub">Твой прогресс, ошибки и результаты сохраняются в профиле.</p>${error?`<div class="auth-error">${esc(error)}</div>`:''}<form id="loginForm"><label>Ник<input name="username" minlength="3" maxlength="24" autocomplete="username" required placeholder="Например, Моряк_22"></label><label>Пароль<input name="password" type="password" minlength="6" autocomplete="current-password" required placeholder="Минимум 6 символов"></label><button class="btn btn-primary wide">Войти</button></form><button class="link-btn" id="forgotBtn">Забыли пароль?</button><div class="auth-divider">или</div><button class="btn btn-secondary wide" id="registerBtn">Создать аккаунт</button><p class="auth-note">${AUTH.mode==='local'?'Открыт локальный режим: аккаунт хранится только в этом браузере.':'Облачный режим: аккаунт и прогресс хранятся на сервере.'}</p></div></div>`;document.getElementById('loginForm').onsubmit=async e=>{e.preventDefault();let f=new FormData(e.currentTarget);try{if(AUTH.mode==='cloud'){let d=await authRequest('login',{username:f.get('username'),password:f.get('password')});AUTH.user=d.user}else{localLogin(f.get('username'),f.get('password'))}document.body.classList.remove('auth-open');AUTH.ready=true;await loadState();render()}catch(x){authScreen(x.message)}};document.getElementById('forgotBtn').onclick=()=>forgotScreen();document.getElementById('registerBtn').onclick=()=>registerScreen()}
function forgotScreen(error=''){
  document.body.classList.add('auth-open');
  V.innerHTML=`<div class="auth-shell"><div class="auth-card animate"><div class="auth-logo">✉</div><div class="eyebrow">Восстановление</div><h1>Забыли пароль?</h1><p class="auth-sub">Укажи email, который привязан к аккаунту. Если он найден, мы отправим одноразовую ссылку.</p>${error?`<div class="auth-error">${esc(error)}</div>`:''}<form id="forgotForm"><label>Email<input name="email" type="email" autocomplete="email" required placeholder="name@example.com"></label><button class="btn btn-primary wide">Отправить ссылку</button></form><button class="btn btn-secondary wide" id="forgotBack">Вернуться ко входу</button></div></div>`;
  document.getElementById('forgotForm').onsubmit=async e=>{e.preventDefault();const email=new FormData(e.currentTarget).get('email');try{const d=await authRequest('forgot-password',{email});V.innerHTML=`<div class="auth-shell"><div class="auth-card animate"><div class="auth-logo">✓</div><div class="eyebrow">Письмо отправлено</div><h1>Проверь почту</h1><p class="auth-sub">Если аккаунт с таким email существует, письмо со ссылкой для сброса уже отправляется. Ссылка действует 30 минут.</p><button class="btn btn-secondary wide" id="forgotBack2">Вернуться ко входу</button></div></div>`;document.getElementById('forgotBack2').onclick=()=>authScreen()}catch(x){forgotScreen(x.message)}};
  document.getElementById('forgotBack').onclick=()=>authScreen();
}
function resetScreen(token,error=''){
  document.body.classList.add('auth-open');
  V.innerHTML=`<div class="auth-shell"><div class="auth-card animate"><div class="auth-logo">🔑</div><div class="eyebrow">Новый пароль</div><h1>Сбросить пароль</h1><p class="auth-sub">Придумай новый пароль минимум из 6 символов.</p>${error?`<div class="auth-error">${esc(error)}</div>`:''}<form id="resetForm"><label>Новый пароль<input name="password" type="password" minlength="6" maxlength="128" autocomplete="new-password" required placeholder="Минимум 6 символов"></label><label>Повтори пароль<input name="password2" type="password" minlength="6" maxlength="128" autocomplete="new-password" required placeholder="Ещё раз"></label><button class="btn btn-primary wide">Сохранить новый пароль</button></form></div></div>`;
  document.getElementById('resetForm').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.currentTarget);if(f.get('password')!==f.get('password2'))return resetScreen(token,'Пароли не совпадают');try{await authRequest('reset-password',{token,password:f.get('password')});location.hash='dashboard';document.body.classList.remove('auth-open');await initAuth()}catch(x){resetScreen(token,x.message)}};
}
function registerScreen(error=''){V.innerHTML=`<div class="auth-shell"><div class="auth-card animate"><div class="auth-logo">⚓</div><div class="eyebrow">Новый курсант</div><h1>Создать профиль</h1><p class="auth-sub">Используй ник, по которому тебя будет видно в профиле.</p>${error?`<div class="auth-error">${esc(error)}</div>`:''}<form id="regForm"><label>Ник<input name="username" minlength="3" maxlength="24" required placeholder="Моряк_22"></label><label>Email<input name="email" type="email" maxlength="254" autocomplete="email" required placeholder="name@example.com"></label><label>Пароль<input name="password" type="password" minlength="6" required placeholder="Минимум 6 символов"></label><label>Повтори пароль<input name="password2" type="password" minlength="6" required placeholder="Ещё раз"></label><button class="btn btn-primary wide">Зарегистрироваться</button></form><button class="btn btn-secondary wide" id="backLogin">Уже есть аккаунт</button></div></div>`;document.getElementById('regForm').onsubmit=async e=>{e.preventDefault();let f=new FormData(e.currentTarget);if(f.get('password')!==f.get('password2'))return registerScreen('Пароли не совпадают');try{if(AUTH.mode==='cloud'){let d=await authRequest('register',{username:f.get('username'),email:f.get('email'),password:f.get('password')});AUTH.user=d.user}else{localRegister(f.get('username'),f.get('password'))}document.body.classList.remove('auth-open');AUTH.ready=true;await loadState();render()}catch(x){registerScreen(x.message)}};document.getElementById('backLogin').onclick=()=>authScreen()}
function localUsers(){try{return JSON.parse(localStorage.getItem(LOCAL_USERS))||{}}catch{return{}}}function localHash(s){let h=0;for(let i=0;i<s.length;i++)h=((h<<5)-h+s.charCodeAt(i))|0;return String(h)}
function localRegister(u,p){u=String(u).trim();if(!/^[\p{L}\p{N}_-]{3,24}$/u.test(u))throw Error('Ник: 3–24 символа, буквы, цифры, _ или -');let users=localUsers();if(users[u])throw Error('Такой ник уже занят');users[u]={password:localHash(p),createdAt:new Date().toISOString()};localStorage.setItem(LOCAL_USERS,JSON.stringify(users));localStorage.setItem(LOCAL_SESSION,u);AUTH.user={username:u}}
function localLogin(u,p){let users=localUsers();if(!users[u]||users[u].password!==localHash(p))throw Error('Неверный ник или пароль');localStorage.setItem(LOCAL_SESSION,u);AUTH.user={username:u}}
window.logout=async()=>{if(AUTH.mode==='cloud'){try{await fetch('/api/logout',{method:'POST',credentials:'include'})}catch{}}localStorage.removeItem(LOCAL_SESSION);AUTH.user=null;AUTH.ready=false;S={blocks:{},exam:null,mistakes:{}};authScreen()}
function toast(m){let t=document.getElementById('toast');t.textContent=m;t.classList.add('show');clearTimeout(window.tt);window.tt=setTimeout(()=>t.classList.remove('show'),2200)}
async function initAuth(){applyTheme();const raw=(location.hash||'').slice(1),parts=raw.split('/');if(parts[0]==='reset'&&parts[1]){AUTH.mode='cloud';AUTH.ready=true;resetScreen(decodeURIComponent(parts.slice(1).join('/')));return}try{const r=await fetch('/api/me',{credentials:'include',cache:'no-store'});AUTH.mode='cloud';if(r.ok){let d=await r.json();AUTH.user=d.user;AUTH.ready=true;await loadState();render();return}authScreen();return}catch{AUTH.mode='local'}let u=localStorage.getItem(LOCAL_SESSION);if(u&&localUsers()[u]){AUTH.user={username:u};AUTH.ready=true;await loadState();render()}else authScreen()}
document.querySelectorAll('.nav').forEach(n=>n.onclick=()=>{go(n.dataset.route);document.getElementById('sidebar').classList.remove('open')});document.getElementById('hamb').onclick=()=>document.getElementById('sidebar').classList.toggle('open');document.getElementById('themeToggle').onclick=()=>{localStorage.setItem(THEME_KEY,(localStorage.getItem(THEME_KEY)||'light')==='dark'?'light':'dark');applyTheme()};document.getElementById('reset').onclick=()=>{document.getElementById('modal').classList.remove('hidden');document.getElementById('modal').innerHTML='<div class="modal-box"><h3>Сбросить прогресс?</h3><p>Удалятся результаты блоков, экзамена и список ошибок.</p><div class="modal-actions"><button class="btn btn-secondary" onclick="document.getElementById(\'modal\').classList.add(\'hidden\')">Отмена</button><button class="btn btn-danger" onclick="window.resetProgress()">Сбросить</button></div></div>'};window.resetProgress=async()=>{S={blocks:{},exam:null,mistakes:{}};await save();document.getElementById('modal').classList.add('hidden');render()};window.addEventListener('hashchange',render);initAuth()})();
