name = "shturman-training"
compatibility_date = "2026-09-12"
pages_build_output_dir = "."

[[d1_databases]]
binding = "DB"
database_name = "shturman"
database_id = "9d1c0871-93a7-451f-b821-af1ff2d33b03"

[vars]
ADMIN_USERNAME = "ТВОЙ_НИК"
RESEND_FROM_EMAIL = "Shturman <no-reply@shturman.xyz>"
